name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MC_VERSION: 1.19.4
  VELOCITY_VERSION: 3.2.0-SNAPSHOT
  WATERFALL_VERSION: 1.19

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mcproxy
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: plain
          - name: waterfall
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VELOCITY_VERSION=${{ env.VELOCITY_VERSION }}
            WATERFALL_VERSION=${{ env.WATERFALL_VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ matrix.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ matrix.name }}:${{ env.MC_VERSION }}
